### ISSUE TITLE
Bend Bash needs real photo

### ISSUE THREAD

**Issue by helencramer** [south-bend-code-school/SBCS#41]
![screen shot 2017-01-26 at 2 08 25 pm](https://cloud.githubusercontent.com/assets/25037743/22346138/f30e307c-e3d0-11e6-974c-31b09b996e01.png)

**Comment by julesdelee** [comment]
The photo also doesn't show up for me on my mobile (MotoG - Chrome)
![screenshot_2017-01-30-15-58-33](https://cloud.githubusercontent.com/assets/21960835/22444459/01048472-e711-11e6-953f-f0b36d17e4f9.png)
